### ISSUE TITLE
Réaliser les pièces et assembler le grand robot

### ISSUE THREAD

**Issue by gdepuille** [ARIG-Robotique/robomovies#11]

**Comment by guillaumelemaitre** [comment]
debut de realisation des pieces du gros.
voir photo des bras de tapis dans le drive

**Comment by guillaumelemaitre** [comment]
assemblage partiel bien avancé
voir photo dans le drive

**Comment by guillaumelemaitre** [comment]
assemblage global ok
manque la tourelle de detection a finaliser
