### ISSUE TITLE
Réalisation de la page web

### ISSUE THREAD

**Issue by amandinedaigle** [ARIG-Robotique/robomovies#13]
http://www.planete-sciences.org/robot/poolzor/

Un questionnaire est à remplir sur le site Internet entre le 01 novembre 2014 et le 6 janvier 2015. Chaque équipe est tenue de remplir cette page dans le but de se présenter. Elle doit contenir au minimum : une photo, un logo de l’équipe, une présentation de l’équipe, une description du projet. Vous pouvez également y ajouter le lien de votre site web si vous en possédez un.

**Comment by gdepuille** [comment]
Document initialisé dans le Drive de l'association. En relecture par @amandinedaigle, @heiginko et @guillaumelemaitre.

Soumission le we prochain.

**Comment by gdepuille** [comment]
@ARIG-Robotique/owners : Poster en attente de validation.
