### ISSUE TITLE
Réalisation du document projet

### ISSUE THREAD

**Issue by amandinedaigle** [ARIG-Robotique/robomovies#15]
Un document de quatre pages maximum (avec un nombre illimité d’annexes) est à déposer sur le site Internet entre le 01 novembre 2014 et le 20 janvier 2015. 
La trame de ce document sera à télécharger sur le site d’inscription pendant cette période.

**Comment by gdepuille** [comment]
@ARIG-Robotique/owners : Posté en attente de validation.
