### ISSUE TITLE
Réalisation du poster technique

### ISSUE THREAD

**Issue by amandinedaigle** [ARIG-Robotique/robomovies#16]
Un poster présentant votre équipe et le robot est à réaliser. Ce document devra être rendu entre le 01 novembre 2014 et le 7 avril 2015.

**Comment by gdepuille** [comment]
@guillaumelemaitre : Le poster je te laisserai le faire avec Totoshop. Pour l'impression au boulot on a un traceur, je pense pouvoir faire l'impression du coup.

**Comment by guillaumelemaitre** [comment]
(poster temporaire dans le drive)
comme les robots ont le meme type de visuel chaque annee,
le poster aussi :-)

**Comment by guillaumelemaitre** [comment]
fait
